### ISSUE TITLE
Noisy voice generated when audio dataset have variable amplitude.

### ISSUE THREAD

**Issue by rishikksh20** [r9y9/wavenet_vocoder#137]
I have trained wavenet for a long time but the audio generated is too noisy (there is constant low-frequency noise). It strange because I have trained it in 5 different datasets before but no problem but my current dataset have the problem. don't know the exact reason but I felt that it is due to high variation in amplitude of audios, in my current dataset some audios have high amplitude and some have very low. So does this amplitude variation hurts the result? 
If yes then how I can get rid of it without recording again?

**Comment by AghilasSini** [comment]
Hi @rishikksh20,

I think that have the same issue.
I have trained wavenet_vocoder for more than  660k (iterations), but still, have a noisy voice.
For me, I don't know if  it's due to the amplitude effect or  to the downsampling effect because I downsample my data from 44.1khz to 22.05khz
- Here is an example (https://soundcloud.com/aghilas-sini/checkpoint-step000660000)
