### ISSUE TITLE
Dilation conv kernel size=3

### ISSUE THREAD

**Issue by danshirron** [r9y9/wavenet_vocoder#32]
In hparams kernel_size=3 while in most implementations i came across, kernel size 2 is used.
Does anyone have experience with implications (mainly output quality) of using kernel size=3 vs 2?

**Comment by bryanjp3** [comment]
The original wavenet used filter width of 2 which is why its the most common. In the parallel wavenet paper they increased sampling rate from 16kHz to 24kHz, filter width of 3 and claim better sound quality. Since the sample rate 50% faster and filter width is 50% longer, the convolution is essentially over the same amount of time. So far I have my best results with 3 width filter, 24kHz but I have not compared it to its 16kHz 2 width equivalent because it's not worth the training time.
