### ISSUE TITLE
math.sqrt(0.5)

### ISSUE THREAD

**Issue by PetrochukM** [r9y9/wavenet_vocoder#67]
Hey There!

The Wavenet paper never mentioned multiplying skip connections with ``math.sqrt(0.5)``. What is up with that?

https://github.com/r9y9/wavenet_vocoder/blob/1b571a78ea9e65867c09942ce952fa13e96f57de/wavenet_vocoder/wavenet.py#L224

**Comment by r9y9** [comment]
https://github.com/pytorch/fairseq/blob/4973d05ac7651f46e1c7edc8060600b44baf9e71/fairseq/models/fconv.py#L157

It comes from Deep Voice 3 and https://arxiv.org/abs/1705.03122. The reason is that I wrote code based on https://github.com/r9y9/deepvoice3_pytorch.  Probably work without it.

Same for weight normalization: https://github.com/r9y9/wavenet_vocoder/blob/1b571a78ea9e65867c09942ce952fa13e96f57de/hparams.py#L63-L64.

**Comment by PetrochukM** [comment]
Thank you!

Anything else to watch out for?

Working with the Tacotron 2 authors to reimplement their paper. This means, for example, I am not normalizing my spectrogram to [0, 1]. I did not apply any decibel clipping. Etc.

What else is different in your Wavenet from the original Wavenet? For example, the ReLU during upsampling that I mentioned earlier.

**Comment by tuan3w** [comment]
Hi @r9y9 ,
Currently, I'm not able to access to my GPU to test my hypothesis but I think we should discuss about this number. As I understand, the target of this multiplication is to keep output has same variance as its inputs [[1](http://cs231n.github.io/neural-networks-2/)] [[2](https://arxiv.org/pdf/1706.03762.pdf)]. As from your [code](https://github.com/r9y9/wavenet_vocoder/blob/master/wavenet_vocoder/wavenet.py#L221-L231):
```python
        skips = None
        for f in self.conv_layers:
            x, h = f(x, c, g_bct)
            if skips is None:
                skips = h
            else:
                skips += h
                if self.legacy:
                    skips *= math.sqrt(0.5)

        x = skips
```
In order to maintain the same variance, I think it should be:
```python
        skips = None
        for f in self.conv_layers:
            x, h = f(x, c, g_bct)
            if skips is None:
                skips = h
            else:
                skips += h

        x = skips / math.sqrt(len(self.conv_layers))
```
As in transformer network, the authors claim that it helps when feature dimension is large. As in our case, it will help if number of layers is large. I haven't test it yet, but I think it will improve the performance of model.
Thanks.
